micronaut:
  application:
    name: github-popular-repositories
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

logger:
  levels:
    io.micronaut.http.client: INFO

netty:
  default:
    allocator:
      max-order: 3

githubpopular:
  http:
    urls:
      github: https://api.github.com
